// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf16f6vOsw7O9u0l0SnPaF2p1Uh4OKA6E',
    appId: '1:677004070215:web:6e5d716342de77a2ead062',
    messagingSenderId: '677004070215',
    projectId: 'felix-s-cookbook',
    authDomain: 'felix-s-cookbook.firebaseapp.com',
    databaseURL: 'https://felix-s-cookbook-default-rtdb.firebaseio.com',
    storageBucket: 'felix-s-cookbook.appspot.com',
    measurementId: 'G-KLYWYH51HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvMkLSE54kp_6fgiRR6Wgje_ZenyOnG-g',
    appId: '1:677004070215:android:a1ff0419ff736893ead062',
    messagingSenderId: '677004070215',
    projectId: 'felix-s-cookbook',
    databaseURL: 'https://felix-s-cookbook-default-rtdb.firebaseio.com',
    storageBucket: 'felix-s-cookbook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM-pcxrbaBeO-hVOFL0116kalZw2dTmO0',
    appId: '1:677004070215:ios:a8aadc6f02f2ec21ead062',
    messagingSenderId: '677004070215',
    projectId: 'felix-s-cookbook',
    databaseURL: 'https://felix-s-cookbook-default-rtdb.firebaseio.com',
    storageBucket: 'felix-s-cookbook.firebasestorage.app',
    iosBundleId: 'com.hypius.cookbook.cookbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM-pcxrbaBeO-hVOFL0116kalZw2dTmO0',
    appId: '1:677004070215:ios:a8aadc6f02f2ec21ead062',
    messagingSenderId: '677004070215',
    projectId: 'felix-s-cookbook',
    databaseURL: 'https://felix-s-cookbook-default-rtdb.firebaseio.com',
    storageBucket: 'felix-s-cookbook.firebasestorage.app',
    iosBundleId: 'com.hypius.cookbook.cookbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf16f6vOsw7O9u0l0SnPaF2p1Uh4OKA6E',
    appId: '1:677004070215:web:3a044c0a4a0821f2ead062',
    messagingSenderId: '677004070215',
    projectId: 'felix-s-cookbook',
    authDomain: 'felix-s-cookbook.firebaseapp.com',
    databaseURL: 'https://felix-s-cookbook-default-rtdb.firebaseio.com',
    storageBucket: 'felix-s-cookbook.firebasestorage.app',
    measurementId: 'G-4HC2NMCGFY',
  );

}